### PR TITLE
  #7 one time rake

### PR DESCRIPTION
**Pull request by alan2112000**
1. Create Adapter for different database schema
  2. every adapter has its own user can output the process data
  3. write native sql to insert to database
  4. User in resume genius will be created by the paymenbt profile time
  if user dont have payment profile then created by the user record timestamp

### CODE REVIEW

**Comment by joshsmoore** [comment]
Looks OK, but I think we should add some test cases before we merge

**Comment by alan2112000** [comment]
ok I will add more test in this

**Comment by GGD** [comment]
OK (and remember to remove `binding.pry`)

**Comment by alan2112000** [comment]
remove the binding.pry and add the test by loading csv from the data dump from rc and lt

**Pull request merged**
